app:
  - .github/filter.yaml
  - .github/workflows/app-*.yaml
  - apps/**/*
  - packages/**/*
  - .npmrc
  - package.json
  - pnpm-workspace.yaml
  - turbo.json

website-v2:
  - .github/filter.yaml
  - .github/workflows/website-v2-*.yaml
  - apps/website-v2/**/*
  - packages/**/*
  - .npmrc
  - package.json
  - pnpm-workspace.yaml
  - turbo.json
