api:
  - .github/filter.yml
  - .github/workflows/api-*.yml
  - packages/api/**

client:
  - .github/filter.yml
  - .github/workflows/client-*.yml
  - packages/client/**

graphql:
  - .github/filter.yml
  - .github/workflows/graphql-*.yml
  - packages/api/**
  - packages/client/codegen.ts

docker:
  - .github/filter.yml
  - .github/workflows/docker-*.yml
  - docker/**/*
  - .dockerignore
  - yarn.lock
