version: "3.8"

services:
  app:
    image: ghcr.io/dino3616/shio:latest
    container_name: shio-app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.development
    volumes:
      - type: bind
        source: ../
        target: /workspaces/shio/
      - type: volume
        source: pnpm-store
        target: /workspaces/shio/.pnpm-store/
    tty: true

volumes:
  pnpm-store:
    driver: local
