ARG NODE_VERSION=18

FROM node:${NODE_VERSION}-bullseye

# hadolint ignore=DL3008
RUN apt-get update \
    && apt-get --no-install-recommends -y install gnupg2 ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists \
    && yarn global add pnpm turbo

WORKDIR /shio

COPY ./.git ./.git
COPY ./pnpm-lock.yaml ./pnpm-workspace.yaml ./
COPY ./*/package.json ./*/package.json
RUN pnpm install --frozen-lockfile
