// eslint-disable-next-line no-shadow
export enum InjectionToken {
  TIMELINE_REPOSITORY = 'TIMELINE_REPOSITORY',
  TIMELINE_READER_USE_CASE = 'TIMELINE_READER_USE_CASE',
  SKILL_REPOSITORY = 'SKILL_REPOSITORY',
  SKILL_READER_USE_CASE = 'SKILL_READER_USE_CASE',
}
