name: client build

on: [push, pull_request]

env:
  node-version: 18

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      client: ${{ steps.changes.outputs.client }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/filter.yml

  build-client:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.client == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: install
        run: yarn install --immutable

      - name: build
        run: yarn client build

  client-build-check:
    if: ${{ ! failure() }}
    needs: build-client
    runs-on: ubuntu-latest
    steps:
      - run: echo "build is successfully executed."
